### PR TITLE
Bump grunt-sass to 0.17.0

### PR DESCRIPTION
**Pull request by tombye**

### CODE REVIEW

**Comment by joelanman** [comment]
LGTM, but do we need to standardise on using ~ to prefix version numbers? Or should it be a case by case basis?

I don't have much experience here, but ~ sounds good because it'll allow minor updates (normally bug fixes)

**Comment by tombye** [comment]
I tend to lock dependancies to the exact version so there's no doubt and all changes are part of a manual process which carries an expectation that any impact will be contained by proper testing.

I've also had quite a few incidents where node modules with self-updating version numbers have broken builds where nothing else has changed.

**Comment by joelanman** [comment]
makes sense, so should we lock all?

**Comment by joelanman** [comment]
could easily be looked at in another PR - this one looks fine to me

**Pull request merged**
