### PR TITLE
Split Grunt task into two parts

### PR DESCRIPTION
**Pull request by tombye**
A rebased version of https://github.com/tombye/express_prototype/pull/28

### CODE REVIEW

**Comment by tombye** [comment]
OK, I've removed the requirement for a global grunt command and tested on Heroku with changes to the CSS, JS and with images added. @joelanman can you think of any other scenarios that need testing?

**Comment by joelanman** [comment]
something's got lost somewhere - the environment variable isnt set to `production` any more, so authentication isnt activated when pushed to heroku like it used to be.

**Comment by joelanman** [comment]
hm, just checking and I don't think the production var ever went in, which is weird.

**Comment by joelanman** [comment]
LGTM

**Pull request merged**
