### PR TITLE
Update package.json to only use dependencies

### PR DESCRIPTION
**Pull request by gemmaleigh**
- Remove dev dependencies
- Use the same version of node-sass and grunt-sass as GOV.UK elements
for Sass placeholder support (using the govuk frontend toolkit
placeholders for grid layout and clearing floated content).

### CODE REVIEW

**Comment by tombye** [comment]
Can this also include locking the versions down (removing any carets or tildes so modules can't update themselves)?

**Comment by gemmaleigh** [comment]
Do we not want to use the most up-to-date versions of our own tools? If we
keep the tilde for the template and toolkit then we can receive minor
updates for both.

On 20 January 2015 at 11:36, Tom Byers <notifications@github.com> wrote:

> Can this also include locking the versions down (removing any carets or
> tildes so modules can't update themselves)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tombye/express_prototype/pull/43#issuecomment-70641069>
> .
>



-- 
Gemma Leigh
Government Digital Service
3rd Floor, Aviation House, 125 Kingsway, London WC2B 6NH
T: 07990 812121

**Comment by tombye** [comment]
We do and we can still receive those updates but it will be through a controlled, manual process & one that doesn't introduce the case where users could be running the app with a different set of dependancies to us, just because they've run `npm install` some time after we last did.

**Comment by tombye** [comment]
Sorry, misread your comment so replied incorrectly. I'd say yes, we could keep those as you say because we control their publishing.

**Pull request merged**
